name: Deployment example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  deployments: write
  id-token: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Prepare Rust
      run: rustup toolchain install stable --profile minimal
    
    - name: Setup cache
      uses: Swatinem/rust-cache@v2
    
    - name: Install Rumage
      run: cargo install rumage

    - name: Build
      run: rumage build -s example -b build
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: './build'
          
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
